version: "3"
services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "80:80"
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  groomer_talk_1:
    image: zzzinho/groomer_talk:latest
    container_name: groomer_talk_1
    expose: 
      - "3000"
    volumes: 
      - /src/groomer_talk_1:/src
      - /src/node_modules
    environment:
      - TZ=Asia/Seoul
    restart: "unless-stopped"