version: "3"
services: 
  proxy:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "80:80"
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  groomer_talk:
    image: zzzinho/groomer_talk:latest
    container_name: groomer_talk
    expose: 
      - "3000"
    volumes: 
      - /src/groomer_talk:/src
      - /src/node_modules
    restart: "unless-stopped"